version: '3'
services:
    searcher:
        image: mitubaex/inpochi:1.1
        ports:
            - "9000:9000"
        volumes:
            - ./:/app
        tty: true
        command: bash -c "cd /app && export PATH=$PATH:/opt/activator && activator run"
    solr:
        image: solr
        ports:
            - "8983:8983"
        volumes:
            - ./data:/opt/solr/data
