searcher:
    image: ingensi/play-framework
    # image: dordoka/play-framework
    ports:
        - "9000:9000"
    # tty: true
    volumes:
        - ./:/app
    # command: bash -c "cd /app && bash script.sh && activator run"

