version: '3'
services:
    searcher:
        # image: hseeberger/scala-sbt
        # image: ingensi/play-framework
        # image: dordoka/play-framework
        image: mitubaex/inpochi
        ports:
            - "9000:9000"
        # tty: true
        volumes:
            - ./:/app
        tty: true
        command: bash -c "cd /app && sbt run"
        # command: bash -c "echo hello"

